project_id = "mjedmtpnmszfzzaaqvui"

[functions.send-booking-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-customer-reply]
verify_jwt = true

[functions.send-booking-reminder]
verify_jwt = false